project:
  type: book
  output-dir: docs
  resources:
    - images

execute:
  freeze: auto
  echo: true
  dev: "ragg_png"
  dpi: 740
  out.width: "100%"
  fig.width: 6
  fig.asp: 0.618
  fig.retina: 3
  fig.align: "center"
  fig.show: "hold"

book:
  title: "Refactoring Provider"
  subtitle: "Building A Better `{provider}`"
  author: "Andrew Allen Bruce"
  date: today
  description: |
    This is a personal, informal guide to rewriting an R package. It is a work in progress and will be updated as I learn more about the process.
  site-url: https://andrewallenbruce.github.io/providerdev/
  repo-url: https://github.com/andrewallenbruce/providerdev
  repo-actions: [source]
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  chapters:
    - index.qmd
    - overview.qmd
    - part: "FAQs"
      chapters:
        - faq_public.qmd
        - faq_provider.qmd
        - faq_schema.qmd
        - faq_syntax.qmd
    - part: "Catalogs"
      chapters:
        - api_public.qmd
        - api_provider.qmd
        - api_openpayments.qmd
    - part: "Endpoints"
      chapters:
        - end_affiliations.qmd
        - end_enrollees.qmd
        - end_qualityeligibility.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    anchor-sections: true
    smooth-scroll: true
    code-links:
      - text: Provider GitHub
        icon: file-code
        href: https://github.com/andrewallenbruce/provider
