project:
  type: book
  output-dir: docs
  resources:
    - includes/_common.R
    - figures
    - data

book:
  title: "Refactoring <b>provider</b><sup><i>2</i></sup>"
  subtitle: "Notes for Building A Better `{provider}`"
  author: "Andrew Allen Bruce"
  date: today
  description: |
    This is a personal, informal guide to rewriting an R package. It is a work in progress and will be updated as I learn more about the process.
  site-url: https://andrewallenbruce.github.io/providerdev/
  repo-url: https://github.com/andrewallenbruce/providerdev
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    border: false
    pinned: true
    background: light
  chapters:
    - index.qmd

    - part: overview.qmd
      chapters:
        - wk_backend.qmd
        - wk_groups.qmd
        - wk_url.qmd
        - wk_args.qmd
        - wk_query.qmd
        - wk_download.qmd
        - wk_search.qmd
        - wk_describe.qmd

    - part: "APIs"
      chapters:
        - api_nppes.qmd
        - api_qpp.qmd
        - api_ndc.qmd

    - part: api_care.qmd
      chapters:
        - care_ahqr.qmd
        - care_aip.qmd
        - care_cpc.qmd
        - care_joint.qmd
        - care_countyrisk.qmd
        - care_drahac.qmd
        - care_esrdgrp.qmd
        - care_enrollees.qmd
        - care_rhc.qmd

    - part: api_prov.qmd
      chapters:
        - pro_affiliations.qmd

    - part: api_open.qmd
      chapters:
        - open_dashboard.qmd
        - open_national.qmd
        - open_state.qmd
        - open_nature.qmd
        - open_specialty.qmd
        - open_covered.qmd
        - open_physician.qmd
        - open_information.qmd
        - open_entity.qmd
        - open_teaching.qmd

    - part: api_mcd.qmd
      chapters:
        - caid_acaful.qmd
        - caid_rebate.qmd

    - part: api_hc.qmd
      chapters:
        - hgov_auto.qmd
        - hgov_abreg.qmd
        - hgov_absus.qmd

    - part: "Demos"
      chapters:
        - demo_geo.qmd
        - demo_bslib.qmd

  appendices:
    - faq_syntax.qmd
    - faq_schema.qmd

format:
  html:
    theme: [simplex, custom.scss]
    grid:
      body-width: 900px
    number-depth: 1
    anchor-sections: true
    smooth-scroll: true
    freeze: auto
    code-block-bg: true
    code-copy: true
    code-link: true
    code-tools:
      source: true
      toggle: false
      caption: none
    code-links:
      - text: Provider GitHub
        icon: file-code
        href: https://github.com/andrewallenbruce/provider
      - text: providertwo
        icon: file-code
        href: https://github.com/andrewallenbruce/providertwo
    include-in-header:
      - text: |
          <style type="text/css">
          div.sourceCode > pre.sourceCode.r::before {
            content: 'R';
            display: block;
            text-align: left;
            font-size: 1em;
            margin-bottom: 7px;
            border-bottom: #4c4c4c 1px solid;
            padding-left: 4.25px;
            padding-bottom: 5px;
            color: #aaaaaa;
          }
          </style>

crossref:
    appendix-delim: ":"

execute:
  freeze: false

editor: source


