project:
  type: book
  output-dir: docs
  resources:
    - images/
    - assets/

highlight-style: tango

book:
  title: "provider DevNotes"
  subtitle: "A personal guide to rewriting an R package"
  author: "Andrew Allen Bruce"
  description: |
    This is a personal guide to rewriting an R package. It is a work in progress and will be updated as I learn more about the process.

  site-url: https://andrewallenbruce.github.io/providerdev/
  repo-url: https://github.com/andrewallenbruce/providerdev
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  reader-mode: true


  chapters:
    - index.qmd
    - overview.qmd

    - part: core.qmd
      chapters:
        - affiliations.qmd
        - nppes.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: source

