project:
  type: book
  output-dir: docs
  resources:
    - includes
    - figures
    - data

book:
  title: "Refactoring <b>provider</b><sup><i>2</i></sup>"
  subtitle: "Notes for Building A Better `{provider}`"
  author: "Andrew Allen Bruce"
  date: today
  description: |
    This is a personal, informal guide to rewriting an R package. It is a work in progress and will be updated as I learn more about the process.
  site-url: https://andrewallenbruce.github.io/providerdev/
  repo-url: https://github.com/andrewallenbruce/providerdev
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    border: false
    pinned: true
    background: light
  chapters:
    - index.qmd
    - part: overview.qmd
      chapters:
        - wk_backend.qmd
        - wk_groups.qmd
        - wk_url.qmd
        - wk_args.qmd
        - wk_query.qmd
        - wk_download.qmd
        - wk_search.qmd
    - part: "APIs"
      chapters:
        - api_nppes.qmd
        - api_qpp.qmd
        - api_ndc.qmd
    - part: api_care.qmd
      chapters:
        - care_ahqr.qmd
        - care_aip.qmd
        - care_cpc.qmd
        - care_joint.qmd
        - care_countyrisk.qmd
        - care_drahac.qmd
        - care_esrdgrp.qmd
        - care_enrollees.qmd
        - care_rhc.qmd
    - part: api_prov.qmd
      chapters:
        - pro_affiliations.qmd
    - part: api_open.qmd
      chapters:
        - open_summary.qmd
    - part: api_mcd.qmd
      chapters:
        - mcd_place.qmd
    - part: api_hc.qmd
      chapters:
        - hc_place.qmd
    - part: "Demos"
      chapters:
        - demo_geo.qmd
  appendices:
    - faq_syntax.qmd
    - faq_schema.qmd

format:
  html:
    theme:
      - brand
    number-depth: 1
    anchor-sections: true
    smooth-scroll: true
    tbl-cap-location: bottom
    fig-cap-location: bottom
    echo: true
    message: false
    warning: false
    error: true
    freeze: auto
    dev: "ragg_png"
    dpi: 300
    out.width: "100%"
    fig.width: 8
    fig.height: 5
    fig.asp: 0.618
    fig.retina: 3
    fig.align: "center"
    fig.show: "hold"
    highlight-style: tango
    code-block-bg: true
    code-copy: true
    code-link: true
    code-tools:
      source: true
      toggle: false
      caption: none
    code-links:
      - text: Provider GitHub
        icon: file-code
        href: https://github.com/andrewallenbruce/provider
      - text: providertwo
        icon: file-code
        href: https://github.com/andrewallenbruce/providertwo

crossref:
    appendix-delim: ":"

execute:
  freeze: auto

editor_options:
   chunk_output_type: console


