project:
  type: book
  output-dir: docs
  resources:
    - includes
    - figures
    - data

book:
  title: "Refactoring Provider"
  subtitle: "Notes for Building A Better `{provider}`"
  author: "Andrew Allen Bruce"
  date: today
  description: |
    This is a personal, informal guide to rewriting an R package. It is a work in progress and will be updated as I learn more about the process.
  site-url: https://andrewallenbruce.github.io/providerdev/
  repo-url: https://github.com/andrewallenbruce/providerdev
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  chapters:
    - index.qmd
    - overview.qmd
    - part: "Notes"
      chapters:
        - faq_public.qmd
        - faq_provider.qmd
        - faq_openpay.qmd
        - faq_eligibility.qmd
        - faq_schema.qmd
        - faq_syntax.qmd
    - part: "Work Areas"
      chapters:
        - wk_backend.qmd
        - wk_url.qmd
        - wk_query.qmd
        - wk_offset.qmd
    - part: "Endpoints"
      chapters:
        - end_affiliations.qmd
        - end_enrollees.qmd

format:
  html:
    theme: [cosmo, includes/new.scss]
    monofont: JetBrains Mono
    anchor-sections: true
    smooth-scroll: true
    tbl-cap-location: bottom
    fig-cap-location: bottom
    message: false
    warning: false
    freeze: auto
    echo: true
    dev: "ragg_png"
    dpi: 740
    out.width: "100%"
    fig.width: 6
    fig.asp: 0.618
    fig.retina: 3
    fig.align: "center"
    fig.show: "hold"
    code-links:
      - text: Provider GitHub
        icon: file-code
        href: https://github.com/andrewallenbruce/provider

execute:
  freeze: auto
  echo: true
  dev: "ragg_png"
  dpi: 740
  out.width: "100%"
  fig.width: 6
  fig.asp: 0.618
  fig.retina: 3
  fig.align: "center"
  fig.show: "hold"

pdf:
  documentclass: scrreprt

editor_options:
   chunk_output_type: console


