project:
  type: book
  output-dir: docs
  resources:
    - includes
    - figures
    - data

book:
  title: "Refactoring Provider"
  subtitle: "Notes for Building A Better `{provider}`"
  author: "Andrew Allen Bruce"
  date: today
  description: |
    This is a personal, informal guide to rewriting an R package. It is a work in progress and will be updated as I learn more about the process.
  site-url: https://andrewallenbruce.github.io/providerdev/
  repo-url: https://github.com/andrewallenbruce/providerdev
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    border: true
    pinned: true
    background: light
  chapters:
    - index.qmd
    - overview.qmd
    - part: "APIs"
      chapters:
        - api_main.qmd
        - api_prov.qmd
        - api_open.qmd
        - api_mcd.qmd
        - api_hc.qmd
        - api_nppes.qmd
        - api_qpp.qmd
        - api_ndc.qmd
    - part: "Work Areas"
      chapters:
        - wk_backend.qmd
        - wk_groups.qmd
        - wk_url.qmd
        - wk_query.qmd
        - wk_download.qmd
        - wk_search.qmd
    - part: "Endpoints"
      chapters:
        - end_affiliations.qmd
        - end_enrollees.qmd
    - part: "Demos"
      chapters:
        - demo_geo.qmd
  appendices:
      - faq_syntax.qmd
      - faq_schema.qmd

format:
  typst: default
  html:
    theme:
      - cosmo
      - brand
    number-depth: 1
    anchor-sections: true
    smooth-scroll: true
    tbl-cap-location: bottom
    fig-cap-location: bottom
    message: true
    warning: false
    freeze: auto
    echo: true
    dev: "ragg_png"
    dpi: 740
    out.width: "100%"
    fig.width: 8
    fig.asp: 0.618
    fig.retina: 3
    fig.align: "center"
    fig.show: "hold"
    highlight-style: monokai
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-copy: true
    code-link: true
    code-tools:
      source: true
      toggle: false
      caption: none
    code-links:
      - text: Provider GitHub
        icon: file-code
        href: https://github.com/andrewallenbruce/provider
      - text: providertwo
        icon: file-code
        href: https://github.com/andrewallenbruce/providertwo
format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf


execute:
  freeze: auto

pdf:
  documentclass: scrreprt

editor_options:
   chunk_output_type: console


