project:
  type: book
  output-dir: docs
  resources:
    - images

execute:
  freeze: auto
  echo: true
  dev: "ragg_png"
  dpi: 740
  out.width: "80%"
  fig.width: 6
  fig.asp: 0.618
  fig.retina: 3
  fig.align: "center"
  fig.show: "hold"

book:
  title: "Refactoring Provider"
  subtitle: "Building a better version of my package `{provider}`, brick-by-brick"
  author: "Andrew Allen Bruce"
  date: today
  description: |
    This is a personal, informal guide to rewriting an R package that I wrote from the ground up. It is a work in progress and will be updated as I learn more about the process.
  site-url: https://andrewallenbruce.github.io/providerdev/
  repo-url: https://github.com/andrewallenbruce/providerdev
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search: true

  chapters:
    - index.qmd
    - overview.qmd

    - part: "Research"
    - part: "API"
    - part: "Tidy"
    - part: "Core"
      chapters:
        - affiliations.qmd
    - part: "Classification"
    - part: "Reporting"

format:
  html:
    theme: cosmo
    highlight-style: tango
    anchor-sections: true
    smooth-scroll: true
    code-links:
      - text: Provider repo
        icon: file-code
        href: https://github.com/andrewallenbruce/provider

editor: source

