---
title: "DCAT Schema"
editor_options: 
   chunk_output_type: console
---

```{r setup}
#| echo: false
#| message: false
#| warning: false
source("_common.R")

htmltools::tagList(
  btn_link("https://resources.data.gov/resources/dcat-us/", "DCAT Schema"),
  btn_link("https://resources.data.gov/schemas/dcat-us/v1.1/iso8601_guidance/#accrualperiodicity", "ISO8601"))
```

## `dataset` Fields

### `bureauCode`

Federal agencies, combined agency and bureau code from [OMB Circular A-11, Appendix C](https://obamawhitehouse.archives.gov/sites/default/files/omb/assets/a11_current_year/app_c.pdf). 

> __Format__: `015:11`

```{r}
#| label: bureauCode
#| echo: false
bureauCode <- readr::read_csv(
  here::here("data/omb_bureau_codes.csv"), 
  show_col_types = FALSE,
  col_types = readr::cols(
  agency_name = readr::col_character(),
  bureau_name = readr::col_character(),
  agency_code = readr::col_character(),
  bureau_code = readr::col_character(),
  treasury_code = readr::col_character(),
  cgac_code = readr::col_character()),
  name_repair = janitor::make_clean_names) |> 
  dplyr::mutate(
    agency_code = stringr::str_pad(agency_code, width = 3, pad = "0"),
    bureau_code = stringr::str_pad(bureau_code, width = 2, pad = "0"),
    treasury_code = stringr::str_pad(treasury_code, width = 2, pad = "0"),
    cgac_code = stringr::str_pad(cgac_code, width = 3, pad = "0"))

bureauCode
```

### `programCode`

Federal agencies, list the primary program related to this data asset, from the [Federal Program Inventory](https://resources.data.gov/schemas/dcat-us/v1.1/FederalProgramInventory_FY13_MachineReadable_091613.csv). 

> __Format__: `015:001`

```{r}
#| label: programCode
#| echo: false
programCode <- readr::read_csv(
  here::here("data/FederalProgramInventory_FY13_MachineReadable_091613.csv"), 
  show_col_types = FALSE,
  col_types = readr::cols(
  agency_name = readr::col_character(),
  program_name = readr::col_character(),
  additional_information_optional = readr::col_character(),
  agency_code = readr::col_character(),
  program_code = readr::col_character(),
  program_code_pod_format = readr::col_character()),
  name_repair = janitor::make_clean_names)

programCode
```

### `accrualPeriodicity`

```{r}
iso_8601 <- \(x) {
  kit::nswitch(
    x,
    "R/P10Y",   "Decennial",
    "R/P4Y",    "Quadrennial",
    "R/P1Y",    "Annual",
    "R/P0.5M",  "Bimonthly",
    "R/P2M",    "Bimonthly",
    "R/P0.5W",  "Biweekly",
    "R/P2W",    "Biweekly",
    "R/P3.5D",  "Semiweekly",
    "R/P1D",    "Daily",
    "R/P6M",    "Semiannual",
    "R/P2Y",    "Biennial",
    "R/P3Y",    "Triennial",
    "R/P0.33W", "Three Times a Week",
    "R/P0.33M", "Three Times a Month",
    "R/PT1S",   "Continuously Updated",
    "R/P1M",    "Monthly",
    "R/P3M",    "Quarterly",
    "R/P0.5M",  "Semimonthly",
    "R/P4M",    "Three Times a Year",
    "R/P1W",    "Weekly",
    "R/PT1H",   "Hourly")
}
```


```{r}
arrow::read_json_arrow(
  here::here("data/dcat-us_v1.1_schema_catalog.json")) |> 
  unnest(properties) |> 
  unnest(`@context`, names_sep = "_") |> 
  unnest(`@id`, names_sep = "_") |> 
  unnest(`@type`, names_sep = "_") |> 
  unnest(`@type_enum`, names_sep = "_") |> 
  unnest(conformsTo, names_sep = "_") |> 
  unnest(conformsTo_enum, names_sep = "_") |> 
  unnest(describedBy, names_sep = "_") |> 
  unnest(dataset, names_sep = "_") |> 
  unnest(dataset_items, names_sep = "_") |> 
  mutate(dependencies = delist(dependencies),
         required = flatten_column(required)) |> 
  purse()
```


```{r}
schema_dataset <- arrow::read_json_arrow(here::here("data/dcat-us_v1.1_schema_dataset.json"))

schema_dataset |> 
  glimpse()
```


```{r}
schema_distribution <- arrow::read_json_arrow(here::here("data/dcat-us_v1.1_schema_distribution.json"))

schema_distribution |> 
  glimpse()
```

