---
editor_options: 
   chunk_output_type: console
---

```{r}
#| label: setup-common-01
#| include: false
#| warning: false
source("includes/_common.R")
```

# AHRQ PSI-11 Rates {#sec-ahqr}

The __Agency for Healthcare Research and Quality (AHRQ) Patient Safety Indicator 11 (PSI-11) Measure Rates__ dataset provides information on provider-level measure rates regarding one preventable complication (_Postoperative Respiratory Failure_) for Medicare Fee-For-Service discharges. 

[The PSI-11 measure data are solely reported for providers' information and quality improvement purposes and are not a part of the __Deficit Reduction Act (DRA)__, __Hospital-Acquired Condition (HAC) Payment Provision__ or __HAC Reduction Program__.]{.aside}

### Metadata

```{r}
#| label: s7_object
#| echo: false
end  <- care_endpoint("ahqr_psi11")
print_meta(end, "care")
```

### Resources

```{r}
#| label: resources
#| echo: false
print_resources(end)
```

### Dictionary

```{r}
#| label: data_dict
#| echo: false
dict <- new_tbl(
  field = c(
    "HOSP_ID", 
    "ADM_DISC", 
    "RATE", 
    "INTERVAL_LOWER_LIMIT", 
    "INTERVAL_HIGHER_LIMIT", 
    "START_QUARTER", 
    "START_DATE", 
    "END_QUARTER", 
    "END_DATE"
  ),
  description = c(
    "Provider's CCN (6-digit format).", 
    "Provider's number of eligible discharges used for PSI-11 measure calculations.", 
    "Provider's PSI-11 smoothed measure rate (per 1k discharges).", 
    "95% confidence interval lower limit surrounding provider's smoothed measure rate.", 
    "95% confidence interval upper limit surrounding provider's smoothed measure rate.", 
    "First quarter of PSI-11 measure's performance period.", 
    "First date of PSI-11 measure's performance period.", 
    "Last quarter of PSI-11 measure's performance period.", 
    "Last date of PSI-11 measure's performance period."
  )
)
print_dict_tbl(dict)
```

## Data

```{r}
#| label: http_request
#| message: true
#| echo: false
resp <- quick("ahqr_psi11", limit = 5000)

resp <- resp|> 
  mtt(START_DATE           = clock::date_parse(START_DATE, format = "%m/%d/%Y"),
      END_DATE             = clock::date_parse(END_DATE, format = "%m/%d/%Y"),
      ADM_DISC             = as.double(ADM_DISC),
      RATE                 = as.double(RATE),
      INTERVAL_LOWER_LIMIT = as.double(INTERVAL_LOWER_LIMIT),
      INTERVAL_HIGHER_LIMIT= as.double(INTERVAL_HIGHER_LIMIT)) |> 
  sbt(!is.na(RATE))
resp
```

### Distribution

```{r}
#| label: distribution
#| message: false
#| warning: false
#| echo: false
res <- describe_distribution(resp, centrality = c("mean", "median"))
res
```

```{r}
#| label: distribution_plot
#| layout-ncol: 2
#| message: false
#| warning: false
#| echo: false
plots <- plot(res, dispersion = TRUE)
walk(plots, print)
```
