---
title: "Open Payments"
editor_options: 
   chunk_output_type: console
---

```{r setup}
#| echo: false
#| message: false
#| warning: false
source("_common.R")


```


## Dataset

```{r}
dataset_open <- request("https://openpaymentsdata.cms.gov/api/1/metastore/schemas/dataset/items?show-reference-ids") |>
  req_perform() |>
  resp_body_json(simplifyVector = TRUE) |> 
  tibble() |> 
  unnest_wider(keyword, names_sep = "_") |>
  unnest_wider(theme, names_sep = "_") |>
  unnest_wider(contactPoint, names_sep = "_") |>
  unnest_wider(publisher, names_sep = "_") |> 
  unnest_wider(publisher_data, names_sep = "_") |> 
  mutate(
    description = clean_open_description(description),
    bureauCode = delist(bureauCode),
    programCode = delist(programCode)) |>
  rename_with(remove_at_symbol) |> 
  rename(modified_dttm = `%modified`)

dataset_open |> 
  purse()
```


## Distribution

```{r}
distribution_open <- dataset_open |> 
  select(distribution) |> 
  unnest(distribution) |> 
  unnest(data) |> 
  unnest(`%Ref:downloadURL`, names_sep = "_") |> 
  unnest(`%Ref:downloadURL_data`, names_sep = "_") |> 
  rename_with(replace_open_columns)

distribution_open |> 
  purse()
```
