---
title: "Main"
editor_options: 
   chunk_output_type: console
---

```{r setup}
#| echo: false
#| message: false
#| warning: false
source("_common.R")
```

## Catalog

```{r}
#| label: catalog
main <- main_data_rcpp()

main
```

### Dataset

```{r}
#| label: dataset
main[["dataset"]] |> 
  tidyr::unnest_wider(contactPoint, names_sep = "_") |>
  tidyr::unnest_wider(publisher, names_sep = "_") |> 
  collapse::frename(remove_at_symbol) |> 
  remove_all_na() |> 
  purse()
```

### Distribution: Latest

```{r}
#| label: distribution_latest
main[["distribution_latest"]]
```

### Distribution: API

```{r}
#| label: distribution_api
main[["distribution_api"]]
```

### Distribution: CSV

```{r}
#| label: distribution_csv
main[["distribution_csv"]]
```

### `S7` Classes

#### `Distribution`

```{r}
#| label: Distribution_class
# Distribution <- new_class(
#   name = "Distribution",
#   properties = list(
#     
#   )
# )
```

#### `contactPoint`

```{r}
#| label: contactPoint_class
contactPoint <- new_class(
  name = "contactPoint",
  properties = list(
    type = new_property(class_character, default = "vcard:Contact"),
    fn = class_character,
    hasEmail = class_character
  )
)
```

#### `publisher`

```{r}
#| label: publisher_class
publisher <- new_class(
  name = "publisher",
  properties = list(
    type = new_property(class_character, default = "org:Organization"),
    name = new_property(class_character, default = "Centers for Medicare & Medicaid Services")
  )
)
```

#### `Dataset`

```{r}
#| label: Dataset_class
Dataset <- new_class(
  name = "Dataset",
  properties = list(
    type               = new_property(class_character, default = "dcat:Dataset"),
    accessLevel        = new_property(class_character, default = "public"),
    accrualPeriodicity = class_character,
    bureauCode         = new_property(class_character, default = "009:38"),
    contactPoint       = new_property(contactPoint, default = contactPoint()),
    describedBy        = class_character,
    dataQuality        = new_property(class_logical, default = TRUE),
    description        = class_character,
    distribution       = class_data.frame,
    identifier         = class_character,
    keyword            = class_character,
    landingPage        = class_character,
    language           = class_character,
    license            = class_character,
    modified           = class_Date,
    programCode        = new_property(class_character, default = "009:000"),
    publisher          = new_property(publisher, default = publisher()),
    references         = class_character,
    temporal           = class_character,
    theme              = class_character,
    title              = class_character,
    describedByType    = class_character
  ))

Dataset()
```

#### `Catalog`

```{r}
#| label: Catalog_class
Catalog <- new_class(
  name = "Catalog",
  properties = list(
    type        = new_property(class_character, default = "dcat:Catalog"),
    context     = new_property(class_character, default = "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld"),
    id          = class_character,
    conformsTo  = new_property(class_character, default = "https://project-open-data.cio.gov/v1.1/schema"),
    describedBy = new_property(class_character, default = "https://project-open-data.cio.gov/v1.1/schema/catalog.json"),
    dataset = new_property(Dataset, default = Dataset())
  )
)

Catalog()
```

