---
title: "Main"
editor_options: 
   chunk_output_type: console
---

```{r setup}
#| echo: false
#| message: false
#| warning: false
source("_common.R")
```

```{r}
catalog_data_json <- \() {
  
  metadata <- arrow::read_json_arrow(
    file = "https://data.cms.gov/data.json", 
    col_select = c("@context", "@id", "@type", "conformsTo", "describedBy"),
    as_data_frame = FALSE) |> 
  dplyr::collect()
  
  data_json <- arrow::read_json_arrow(
  file = "https://data.cms.gov/data.json",
  col_select = c("dataset"),
    as_data_frame = TRUE) |> 
  arrow::to_duckdb()
}
```


```{r}
#| label: data_json_metadata
read_json_arrow(
    file = "https://data.cms.gov/data.json", 
    col_select = c("@context", "@id", "@type", "conformsTo", "describedBy"),
    as_data_frame = FALSE) |> 
  collect() |> 
  purse()
```

```{r}
#| label: data_json
data_json <- read_json_arrow(
  file = "https://data.cms.gov/data.json",
  col_select = c("dataset"),
    as_data_frame = TRUE) |> 
  to_duckdb()

dataset_data_json <- data_json |> 
  pull(dataset) |> 
  pluck(1) |> 
  tibble() |> 
  mutate(
    distribution = NULL,
    bureauCode = delist(bureauCode),
    keyword = map_chr(keyword, \(x) paste0(delist(x), collapse = ", ")),
    language = delist(language),
    programCode = delist(programCode),
    theme = map_chr(theme, \(x) paste0(delist(x), collapse = ", ")),
    references = delist(references)) |>
  unnest_wider(contactPoint, names_sep = "_") |>
  unnest_wider(publisher, names_sep = "_")

dataset_data_json |> purse()

distribution_data_json <- data_json |> 
  pull(dataset) |> 
  pluck(1) |> 
  tibble() |> 
  select(distribution) |> 
  unnest(distribution)

distribution_data_json |> purse()
```
