# `rural_health` {#sec-rhc}

```{r}
#| label: setup-common-01
#| include: false
source("includes/_common.R")
```

```{r}
underscore <- \(x) gsub("___owner$", "", x, perl = TRUE)
char_binary <- \(x) val_match(x, "N" ~ 0L, "Y" ~ 1L)
pct_prop <- \(x) {
  cheapr::case(
    x == "0" ~ 0,
    cheapr::is_na(x) ~ NA_real_,
    .default = as.double(x) / 100
  )
}
```


## Rural Health Clinics

> RHC Enrollments

• __Rows__ [5.3k]
• __Pages__ [2]
• __Fields__ [20]

```{r}
rhc_enroll <- careGroup("rural_health")@groups |>
  _[["rural_health_clinic_enrollments"]] |>
  _[["endpoints"]] |>
  _[["identifier"]] |>
  providertwo:::quick_care() |>
  mtt(incorporation_date = providertwo:::as_date(incorporation_date),
      multiple_npi_flag = char_binary(multiple_npi_flag),
      address = cheapr_if_else(
        cheapr::is_na(address_line_2), 
        address_line_1, 
        paste(address_line_1, address_line_2))) |>
  slt(
    npi,
    has_mult_npi = multiple_npi_flag,
    ccn,
    pac = associate_id,
    enid = enrollment_id,
    enid_state = enrollment_state,
    org_name = organization_name,
    dba_name = doing_business_as_name,
    inc_date = incorporation_date,
    inc_state = incorporation_state,
    org_type = organization_type_structure,
    org_type_2 = organization_other_type_text,
    proprietary_nonprofit,
    address,
    city,
    state,
    zip = zip_code)

rhc_enroll |> 
  purse()
```

> RHC Owners

• __Rows__ [62.7k]
• __Pages__ [13]
• __Fields__ [34]

```{r}
rhc_owners <- careGroup("rural_health")@groups |> 
  _[["rural_health_clinic_all_owners"]] |> 
  _[["endpoints"]] |> 
  _[["identifier"]] |> 
  providertwo:::quick_care()

rhc_owners|>
  rnm(
    enid     = enrollment_id,
    pac      = associate_id, 
    org_name = organization_name) |>
  set_names(underscore) |> 
  mtt(
    association_date = providertwo:::as_date(association_date),
    address = cheapr_if_else(
      cheapr::is_na(address_line_2), 
      address_line_1, 
      paste(address_line_1, address_line_2)),
    prop_ownership = pct_prop(percentage_ownership),
    percentage_ownership = as.numeric(percentage_ownership),
    role_code = as.integer(role_code)
  ) |>
  slt(
    pac,
    enid,
    org_name,
    pac_owner = associate_id, 
    org_name_owner = organization_name,
    entity = type,
    role_code,
    role_text,
    date_assoc = association_date,
    first_name,
    middle_name,
    last_name,
    title,
    dba_name = doing_business_as_name,
    address,
    city,
    state,
    zip = zip_code,
    percentage_ownership,
    prop_ownership,
    is_acquisition = created_for_acquisition,
    is_corporation = corporation,
    is_llc = llc,
    is_supplier = medical_provider_supplier,
    is_management = management_services_company,
    is_staffing = medical_staffing_company,
    is_holding = holding_company,
    is_investment = investment_firm,
    is_financial = financial_institution,
    is_consulting = consulting_firm,
    is_forprofit = for_profit,
    is_nonprofit = non_profit,
    is_other = other_type,
    other_desc = other_type_text
  ) |> 
  mtt(
    entity = cheapr::factor_(entity),
    is_acquisition = char_binary(is_acquisition),
    is_corporation = char_binary(is_corporation),
    is_llc = char_binary(is_llc),
    is_supplier = char_binary(is_supplier),
    is_management = char_binary(is_management),
    is_staffing = char_binary(is_staffing),
    is_holding = char_binary(is_holding),
    is_investment = char_binary(is_investment),
    is_financial = char_binary(is_financial),
    is_consulting = char_binary(is_consulting),
    is_forprofit = char_binary(is_forprofit),
    is_nonprofit = char_binary(is_nonprofit),
    is_other = char_binary(is_other)
  ) |> 
  roworder(role_code)
```
