---
title: "DCAT Metadata"
editor_options: 
   chunk_output_type: console
---

```{r}
#| label: setup-common-01
#| include: false
source("includes/_common.R")

gt_tab <- \(x, size = 14) {
  x |>
    gt::gt() |>
    gtUtils::gt_theme_athletic() |>
    gt::tab_options(
      quarto.disable_processing = TRUE,
      column_labels.font.weight = "bolder",
      column_labels.font.size = (size + 4),
      column_labels.background.color = "black",
      column_labels.border.bottom.color = "white",
      table.font.size = size,
      # row_group.font.size = (size + 2),
      table.width = gt::pct(100)) |> 
    gt::cols_align(align = "left", columns = gt::everything()) |> 
    gt::sub_missing(columns = gt::everything(), missing_text = "-")
}


# htmltools::tagList(
#   btn_link(
#     "https://resources.data.gov/resources/dcat-us/", 
#     "DCAT Schema"),
#   btn_link(
#     "https://resources.data.gov/schemas/dcat-us/v1.1/iso8601_guidance/#accrualperiodicity", 
#     "ISO8601"))
```

* [Data Catalog Vocabulary (DCAT) - Version 3](https://www.w3.org/TR/vocab-dcat/)

## JSON Schemas

::: panel-tabset

### Catalog

```{r}
#| label: schema_catalog
#| echo: false
here::here("data/dcat-us_v1.1_schema_catalog.json") |> 
  RcppSimdJson::fload() |> 
  jsonify::pretty_json()
```


### Dataset

```{r}
#| label: schema_dataset
#| echo: false
here::here("data/dcat-us_v1.1_schema_dataset.json") |> 
  RcppSimdJson::fload() |> 
  jsonify::pretty_json()
```

### Distribution

```{r}
#| label: schema_distribution
#| echo: false
here::here("data/dcat-us_v1.1_schema_distribution.json") |> 
  RcppSimdJson::fload() |> 
  jsonify::pretty_json()
```

:::

## Reference Datasets

::: panel-tabset

### `accrualPeriodicity`

```{r}
#| label: accrualPeriodicity
#| echo: false
tibble(
  Periodicity = c(
    "R/PT1S",
    "R/PT1H",
    "R/P1D",
    "R/P3.5D",
    "R/P0.33W",
    "R/P0.5W",
    "R/P1W",
    "R/P2W",
    "R/P0.33M",
    "R/P0.5M",
    "R/P1M",
    "R/P2M",
    "R/P3M",
    "R/P4M",
    "R/P6M",
    "R/P1Y",
    "R/P2Y",
    "R/P3Y",
    "R/P4Y",
    "R/P10Y"
  ),
  Description = providertwo:::fmt_periodicity(Periodicity)
) |> 
  gt_tab()
```

### `bureauCode`

Federal agencies, combined agency and bureau code from [OMB Circular A-11, Appendix C](https://obamawhitehouse.archives.gov/sites/default/files/omb/assets/a11_current_year/app_c.pdf).

> **Format**: `015:11`

```{r}
#| label: bureauCodes
#| echo: false
read_csv(
  here("data/omb_bureau_codes.csv"),
  show_col_types  = FALSE,
  col_types       = cols(
    `Agency Name`   = col_character(),
    `Bureau Name`   = col_character(),
    `Agency Code`   = col_character(),
    `Bureau Code`   = col_character(),
    `Treasury Code` = col_character(),
    `CGAC Code`     = col_character()
  )
) |>
  mutate(
    `Agency Code`   = str_pad(`Agency Code`, width = 3, pad = "0"),
    `Bureau Code`   = str_pad(`Bureau Code`, width = 2, pad = "0"),
    `Treasury Code` = str_pad(`Treasury Code`, width = 2, pad = "0"),
    `CGAC Code`     = str_pad(`CGAC Code`, width = 3, pad = "0"),
    `Agency Name`   = paste0(`Agency Name`, " [", `Agency Code`, "]"),
    `Agency Code`   = NULL,
    `Bureau Name`   = paste0(`Bureau Name`, " [", `Bureau Code`, "]"),
    `Bureau Code`   = NULL
  ) |>
  group_by(`Agency Name`) |> 
  gt_tab()
```

### `programCode`

Federal agencies, list the primary program related to this data asset, from the [Federal Program Inventory](https://resources.data.gov/schemas/dcat-us/v1.1/FederalProgramInventory_FY13_MachineReadable_091613.csv).

> **Format**: `015:001`

```{r}
#| label: programCodes
read_csv(
  here(
    "data/FederalProgramInventory_FY13_MachineReadable_091613.csv"
  ),
  show_col_types                      = FALSE,
  col_types                           = cols(
    `Agency Name`                       = col_character(),
    `Program Name`                      = col_character(),
    `Additional Information (optional)` = col_character(),
    agencyCode                          = col_character(),
    ProgramCode                         = col_character(),
    ProgramCodePODFormat                = col_character()
  )
) |>
  reframe(
    `Agency Name`   = paste0(`Agency Name`, " [", agencyCode, "]"),
    `Program Name`   = paste0(`Program Name`, " [", ProgramCodePODFormat, "]"),
    "Additional Information"   = `Additional Information (optional)`
  ) |>
  group_by(`Agency Name`) |> 
  gt_tab()
```


::: 


<hr>
