---
title: "Providers"
editor_options: 
   chunk_output_type: console
---

```{r setup}
#| echo: false
#| message: false
#| warning: false
source("_common.R")

htmltools::tagList(
  btn_link(
    "https://andrewallenbruce.github.io/provider/reference/providers.html",
    "Documentation"),
  btn_link(
    "https://github.com/andrewallenbruce/provider/blob/main/R/providers.R", 
    "Source"))
```

   * Base URL: `https://data.cms.gov/data-api/v1/`
   * Identifier: `2457ea29-fc82-48b0-86ec-3b0755de7515`

## Catalog

```{r}
#| label: main_catalog
main <- main_data_rcpp()

main
```

## Dataset

```{r}
#| label: provider_dataset
provider_dataset <- collapse::fsubset(
  main[["dataset"]], 
  fuimus::sf_detect(
    title, 
    "Fee-For-Service"
    ))

provider_dataset |> 
  purse()
```

### S7 Class

```{r}
#| label: provider_dataset_class
ProviderDataset <- new_class(
  "ProviderDataset",
  properties = list(
    type               = class_character,
    accessLevel        = class_character,
    accrualPeriodicity = class_character,
    bureauCode         = class_character,
    contactPoint       = class_list,
    describedBy        = class_character,
    dataQuality        = class_logical,
    description        = class_character,
    identifier         = class_character,
    keyword            = class_character,
    landingPage        = class_character,
    language           = class_character,
    license            = class_character,
    modified           = class_Date,
    programCode        = class_character,
    publisher          = class_list,
    references         = class_character,
    temporal           = class_character,
    theme              = class_character,
    title              = class_character,
    describedByType    = class_character
  )
)

ProviderDataset()
```

## Distribution

```{r}
#| label: provider_latest
provider_latest <- collapse::fsubset(
    main[["distribution_latest"]],
    fuimus::sf_detect(
      title, 
      "Fee-For-Service"
      ))

provider_latest |> purse()
```


```{r}
#| label: provider_api
provider_api <- collapse::fsubset(
    main[["distribution_api"]],
    fuimus::sf_detect(
      title, 
      "Fee-For-Service"
      ))

provider_api |> purse()
```


```{r}
#| label: provider_csv
provider_csv <- collapse::fsubset(
    main[["distribution_csv"]],
    fuimus::sf_detect(
      title, 
      "Fee-For-Service"
      ))

provider_csv |> purse()
```

## URLS

```{r}
#| label: urls
list(
  dataset = provider_dataset, 
  latest = provider_latest,
  api = provider_api,
  csv = provider_csv
  )
```


## No. of Results

```{r}
#| eval: false
request(urls$base) |> 
  req_url_path_append(urls$identifier) |> 
  req_url_path_append("stats") |> 
  req_perform() |> 
  resp_body_json(simplifyVector = TRUE)
```

```{r}
#| eval: false
query <- glue::glue(
  '
  "filter[fID{fID}][path]" = "{PATH}",
  "filter[fID{fID}][operator]" = "{OPERATOR}",
  "filter[fID{fID}][value]" = "{VALUE}"
  ', 
  fID = 1:2, 
  PATH = c("STATE_CD", "LAST_NAME"), 
  OPERATOR = "=",
  VALUE = c("GA", "SMITH")
  ) |> 
  glue::glue_collapse(sep = ",\n")

query <- glue::glue('c({query})') |> 
  rlang::parse_expr() |> 
  rlang::eval_bare()

request(urls$base) |> 
  req_url_path_append(urls$identifier) |> 
  req_url_path_append("stats") |> 
  req_url_query(!!!query) |> 
  req_perform() |> 
  resp_body_json(simplifyVector = TRUE)
```

```{r}
#| eval: false
resp <- request(urls$base) |> 
  req_url_path_append(urls$identifier) |> 
  req_url_query(!!!query, size = 5000) |> 
  req_perform()

resp <- RcppSimdJson::fparse(httr2::resp_body_string(resp))

collapse::qTBL(resp[["data"]]) |>
  setNames(c("NPI", "PECOS_ASCT_CNTL_ID", "ENRLMT_ID", 
             "PROVIDER_TYPE_CD", "PROVIDER_TYPE_DESC", 
             "STATE_CD", "FIRST_NAME", "MDL_NAME", 
             "LAST_NAME", "ORG_NAME", "GNDR_SW"))
```


```{r}
#| eval: false
format_syntax <- \(name, value) {
  setNames(
    value, 
    paste0(
      name, 
      "[id-", 
      seq_along(value), 
      "][condition][value]"))
}

format_syntax("filter", c("GA", "NY"))


# query_syntax <- c(
#   "filter[STATE_CD]" = "GA",
#   "filter[LAST_NAME]" = "SMITH"
#   )
```

--------------------------------------------------------------------------------
