---
editor_options: 
   chunk_output_type: console
---

```{r}
#| label: setup-common-01
#| include: false
#| warning: false
source("includes/_common.R")
```

# Summary Dashboard {#sec-opendash}

### Metadata

```{r}
#| label: s7_object
#| echo: false
end  <- open_endpoint("summary_dashboard")
print_meta(end)
```

## Data

```{r}
#| label: http_request
#| message: true
#| echo: false
resp <- quick("summary_dashboard", limit = 500)
resp
```

## Tidyup

```{r}
#| label: tidyup
#| message: false
#| echo: true
x <- resp |> 
    mtt(
      metric = data_metrics,
      type   = case(
        grepl("^Total Number of", metric, perl = TRUE)              ~ "count",
        grepl("^Total Dollar Amount of", metric, perl = TRUE)       ~ "dollar",
        grepl("^Total Dollar Amount Invested", metric, perl = TRUE) ~ "invest",
        grepl("^Total value of interest", metric, perl = TRUE)      ~ "value"),
      data_metrics         = NULL,
      dashboard_row_number = NULL) |>
    rsplit(~ type)

  x$count <-  mtt(
    x$count,
    metric = gsub("^Total Number of ", "", metric, perl = TRUE),
    metric = gsub("^all ", "", metric, perl = TRUE),
    type   = cheapr_if_else(grepl("^Payment Records", metric, perl = TRUE), "record", "entity")) |>
    rsplit( ~ type)

  x$count$entity <- rnm(
    x$count$entity,
    `2017` = py_2017,
    `2018` = py_2018,
    `2019` = py_2019,
    `2020` = py_2020,
    `2021` = py_2021,
    `2022` = py_2022,
    `2023` = py_2023,
    ALL = total) |>
    mtt(
      metric = gsub("Companies Making Payments \\(AM/GPO Making Payment\\)",
                    "Companies [AM/GPO] Making Payments", metric, perl = TRUE),
      metric = gsub("Physician Covered Recipients with associated payment records",
                    "Physicians with Payment Records", metric, perl = TRUE),
      metric = gsub("Non-Physician Practitioner Covered Recipients with associated payment records",
                    "NPPs with Payment Records", metric, perl = TRUE),
      metric = gsub("Teaching Hospitals with associated payment records",
                    "Teaching Hospitals with Payment Records", metric, perl = TRUE)) |>
    pivot(ids = "metric", names = list("year", "count")) |>
    roworder(metric, -year) |>
    colorder(year) |>
    mtt(count = as.integer(count)) |>
    as_tbl()

  x$count$record <- rnm(
    x$count$record,
    `2017` = py_2017,
    `2018` = py_2018,
    `2019` = py_2019,
    `2020` = py_2020,
    `2021` = py_2021,
    `2022` = py_2022,
    `2023` = py_2023,
    ALL = total
  ) |>
    mtt(
      type = case(
        grepl("General Payments", metric, perl = TRUE) ~ "General",
        grepl("Research Payments", metric, perl = TRUE) ~ "Research",
        grepl("Ownership Payments", metric, perl = TRUE) ~ "Ownership",
        .default = "All"
      ),
      status = case(
        grepl("Disputed", metric, perl = TRUE) ~ "Disputed",
        grepl("Undisputed", metric, perl = TRUE) ~ "Undisputed"
      ),
      entity = case(
        grepl("- Covered Recipient", metric, perl = TRUE) ~ "Covered Recipient",
        grepl("- Non-Covered Recipient", metric, perl = TRUE) ~ "Non-Covered Recipient",
        grepl("- Physician or Non-Covered Recipient", metric, perl = TRUE) ~ "Physician or Non-Covered Recipient",
        grepl(
          "- Non-Physician Practitioner or Non-Covered Recipient",
          metric,
          perl = TRUE
        ) ~ "Non-Physician Practitioner or Non-Covered Recipient",
        grepl(" to Physicians", metric, perl = TRUE) ~ "Physician",
        grepl(" to Non-Physician Practitioners", metric, perl = TRUE) ~ "Non-Physician Practitioner",
        grepl(" to Teaching Hospitals", metric, perl = TRUE) ~ "Teaching Hospital",
        grepl(" - Non-Covered Recipient Entity", metric, perl = TRUE) ~ "Non-Covered Recipient Entity",
        grepl(" - Non-Covered Recipient Individual", metric, perl = TRUE) ~ "Non-Covered Recipient Individual"
      ),
      metric = NULL
    ) |>
    pivot(ids = c("type", "status", "entity"),
          names = list("year", "count")) |>
    roworder(type, -year) |>
    colorder(year, type, entity) |>
    mtt(count = as.integer(count)) |>
    as_tbl()

  x$invest <- mtt(
    x$invest,
    metric = gsub("^Total Dollar Amount Invested of all Payment Records ", "", metric, perl = TRUE),
    metric = gsub("^-\\s", "", metric, perl = TRUE))

  x$value <- mtt(
    x$value,
    metric = gsub("^Total value of interest of all Payment Records ", "", metric, perl = TRUE),
    metric = gsub("^-\\s", "", metric, perl = TRUE))

  x$dollar <- mtt(
    x$dollar,
    metric = gsub("^Total Dollar Amount of ", "", metric, perl = TRUE),
    metric = gsub("^all ", "", metric, perl = TRUE))
x
```

### Distribution

```{r}
#| label: distribution
#| message: false
#| warning: false
#| echo: false
# res <- describe_distribution(resp)
# res
```

```{r}
#| label: distribution_plot
#| layout-ncol: 2
#| message: false
#| warning: false
#| echo: false
# plots <- plot(res, dispersion = TRUE)
# walk(plots, print)
```
