---
editor_options: 
   chunk_output_type: console
---

```{r}
#| label: setup-common-01
#| include: false
#| warning: false
source("includes/_common.R")
```

# Summary National {#sec-opennation}

National Level Payment Total and Averages for all Years

### Metadata

```{r}
#| label: s7_object
#| echo: false
end  <- open_endpoint("summary_national")
print_meta(end)
```

## Data

```{r}
#| label: http_request
#| message: true
#| echo: true
fmt_covered <- function(x, what) {
  what <- match.arg(
    what,
    c(
      "Covered Recipient Physician",
      "Covered Recipient Non-Physician Practitioner"
    )
  )
  
  sbt(x, recipient_type == what) |>
    fcompute(
      year            = factor_(program_year),
      payment_type    = factor_(payment_type),
      recipient_type  = what,
      recipient_n     = as.integer(total_number_of_physicians),
      payment_sum     = as.numeric(total_payment_amount_physician),
      payment_mean    = as.numeric(mean_total_payment_amount_physician),
      payment_median  = as.numeric(median_total_payment_amount_physician),
      payments_n      = as.integer(total_payment_count_physician),
      payments_mean   = as.double(mean_total_payment_count_physician),
      payments_median = as.double(median_total_payment_count_physician)
    )
}

resp <- quick("summary_national", limit = 500)

resp <- funique(resp$recipient_type) |>
  map(\(type) fmt_covered(x = resp, what = type)) |>
  rowbind() |>
  mtt(recipient_type = factor_(recipient_type)) |>
  roworder(recipient_type, payment_type) |> 
  print(n = Inf)

describe_distribution(resp, by = "recipient_type")

report::report_sample(resp, by = "recipient_type", n = TRUE)
```

