---
editor_options: 
   chunk_output_type: console
---

```{r}
#| label: setup-common-01
#| include: false
#| warning: false
source("includes/_common.R")
```

# Facility Affiliations {#sec-affiliations}

This is the facility affiliations data publicly reported in the __Provider Data Catalog__.

### Metadata

```{r}
#| label: s7_object
#| echo: false
end  <- pro_endpoint("pdc_affiliations")
print_meta(end)
```

### Dictionary

```{r}
#| label: s7_dictionary
#| echo: false
#| message: false
dict <- list(
  "npi"                                        = "Unique clinician ID assigned by NPPES",
  "ind_pac_id"                                 = "Unique individual clinician ID assigned by PECOS",
  "provider_last_name"                         = "Individual clinician last name",
  "provider_first_name"                        = "Individual clinician first name",
  "provider_middle_name"                       = "Individual clinician middle name",
  "suff"                                       = "Individual clinician suffix",
  "facility_type"                              = "Facilities can fall into the following type categories: Hospitals, Long-term Care Hospital, Nursing Home, Inpatient Rehabilitation Facility, Home Health Agency, Hospice, Dialysis Facility",
  "facility_affiliations_certification_number" = "Medicare CCN of facility type or unit within hospital where an individual clinician provides service",
  "facility_type_certification_number"         = "Medicare CCN of the primary hospital where individual clinician provides service, should the clinician provide services in a unit within the hospital"
)
print_dict_list(dict)
```


## Data

```{r}
#| label: http_request
#| message: true
#| echo: false
resp <- quick("pdc_affiliations", limit = 2000)
resp |> descr()
```

