---
title: "Schema"
editor_options: 
   chunk_output_type: console
---

```{r setup}
#| echo: false
#| message: false
#| warning: false
source("_common.R")

htmltools::tagList(
  btn_link("https://resources.data.gov/resources/dcat-us/", "DCAT Schema"),
  btn_link("https://resources.data.gov/schemas/dcat-us/v1.1/iso8601_guidance/#accrualperiodicity", "ISO8601"),
  btn_link("https://www.drupal.org/docs/core-modules-and-themes/core-modules/jsonapi-module/filtering", "Drupal JSONAPI"))
```

# `dataset` Fields

## `bureauCode`

Federal agencies, combined agency and bureau code from [OMB Circular A-11, Appendix C](https://obamawhitehouse.archives.gov/sites/default/files/omb/assets/a11_current_year/app_c.pdf). 

Use the format of `015:11`.

```{r}
#| label: bureauCode
#| echo: false
bureauCode <- readr::read_csv(
  here::here("data/omb_bureau_codes.csv"), 
  show_col_types = FALSE,
  col_types = readr::cols(
  agency_name = readr::col_character(),
  bureau_name = readr::col_character(),
  agency_code = readr::col_character(),
  bureau_code = readr::col_character(),
  treasury_code = readr::col_character(),
  cgac_code = readr::col_character()),
  name_repair = janitor::make_clean_names) |> 
  dplyr::mutate(
    agency_code = stringr::str_pad(agency_code, width = 3, pad = "0"),
    bureau_code = stringr::str_pad(bureau_code, width = 2, pad = "0"),
    treasury_code = stringr::str_pad(treasury_code, width = 2, pad = "0"),
    cgac_code = stringr::str_pad(cgac_code, width = 3, pad = "0"))

bureauCode
```

## `programCode`

Federal agencies, list the primary program related to this data asset, from the [Federal Program Inventory](https://resources.data.gov/schemas/dcat-us/v1.1/FederalProgramInventory_FY13_MachineReadable_091613.csv). 

Use the format of `015:001`.

```{r}
#| label: programCode
#| echo: false
programCode <- readr::read_csv(
  here::here("data/FederalProgramInventory_FY13_MachineReadable_091613.csv"), 
  show_col_types = FALSE,
  col_types = readr::cols(
  agency_name = readr::col_character(),
  program_name = readr::col_character(),
  additional_information_optional = readr::col_character(),
  agency_code = readr::col_character(),
  program_code = readr::col_character(),
  program_code_pod_format = readr::col_character()),
  name_repair = janitor::make_clean_names)

programCode
```

## `accrualPeriodicity`

```{r}
#| label: accrualPeriodicity
#| echo: false
accrual_key <- c("
Term 	                ISO_8601
Decennial 	          R/P10Y
Quadrennial 	        R/P4Y
Annual 	              R/P1Y
Bimonthly 	          R/P2M or R/P0.5M
Semiweekly 	          R/P3.5D
Daily 	              R/P1D
Biweekly 	            R/P2W or R/P0.5W
Semiannual 	          R/P6M
Biennial 	            R/P2Y
Triennial 	          R/P3Y
Three times a week 	  R/P0.33W
Three times a month 	R/P0.33M
Continuously updated 	R/PT1S
Monthly             	R/P1M
Quarterly 	          R/P3M
Semimonthly 	        R/P0.5M
Three times a year 	  R/P4M
Weekly 	              R/P1W
Hourly 	              R/PT1H
")

accrual_key <- gsub(" \t", ", ", accrual_key)
accrual_key <- gsub("^\n|\n$", "", accrual_key)
accrual_key <- strsplit(accrual_key, "\n")[[1]]
accrual_key <- strsplit(accrual_key, ", ")
accrual_key <- trimws(unlist(accrual_key))
accrual_key <- accrual_key[c(-1, -2)]

accrual_key <- data.frame(
 term = accrual_key[c(TRUE, FALSE)],
 iso_8601 = accrual_key[c(FALSE, TRUE)])

accrual_key
```


```{r}
iso_8601 <- \(x) {
  kit::nswitch(
    x,
    "R/P10Y",   "Decennial",
    "R/P4Y",    "Quadrennial",
    "R/P1Y",    "Annual",
    "R/P0.5M",  "Bimonthly",
    "R/P2M",    "Bimonthly",
    "R/P0.5W",  "Biweekly",
    "R/P2W",    "Biweekly",
    "R/P3.5D",  "Semiweekly",
    "R/P1D",    "Daily",
    "R/P6M",    "Semiannual",
    "R/P2Y",    "Biennial",
    "R/P3Y",    "Triennial",
    "R/P0.33W", "Three Times a Week",
    "R/P0.33M", "Three Times a Month",
    "R/PT1S",   "Continuously Updated",
    "R/P1M",    "Monthly",
    "R/P3M",    "Quarterly",
    "R/P0.5M",  "Semimonthly",
    "R/P4M",    "Three Times a Year",
    "R/P1W",    "Weekly",
    "R/PT1H",   "Hourly")
}

accrual_key |> 
  dplyr::mutate(
    iso_test = iso_8601(iso_8601), .before = 2)
```

