---
title: "Query Syntax"
editor_options: 
   chunk_output_type: console
---

```{r setup}
#| echo: false
#| message: false
#| warning: false
knitr::opts_chunk$set(
  dev        = "ragg_png",
  dpi        = 320,
  out.width  = "100%",
  fig.width  = 8,
  fig.asp    = 0.818,
  fig.retina = 2,
  fig.align  = "center",
  fig.show   = "hold"
)
options(scipen = 999, digits = 3)

library(tidyverse)
library(provider)
library(fuimus)
library(httr2)
library(arrow)
library(terse)
library(emphatic)

purse <- function(x, 
                  pre = "- ", 
                  wid = 0, 
                  sep = " ") {
  terse::terse(
    x = x, 
    prefix = pre, 
    width = wid, 
    config = list(
      gsep = sep, 
      ansi = FALSE))
}
```

## Examples

### Exact Match Search on Column

```r
- dataset   Medicare Fee-For-Service Public Provider Enrollment
  column    PROVIDER_TYPE_DESC 
  equals    PRACTITIONER-GENERAL PRACTICE

call:     /data?
          filter[PROVIDER_TYPE_DESC]=PRACTITIONER%20-%20GENERAL%20PRACTICE
```

```yml
#| label: query_yml
#| eval: false
catalog: "data.json"
format: "API"
description: "latest"
title:  "Medicare Fee-For-Service Public Provider Enrollment"
accessURL: ""

url: 
  scheme: "https://"
  hostname: "data.cms.gov/"
  api: "data-api/v1/dataset/"
  identifier: "d10d792e-ea6e-4145-8512-34efbc1be04b"
  path: "/data?"
  query: 
    - filter: 1
      path: "PROVIDER_TYPE_DESC"
      operator: "EQUALS"
      value: "PRACTITIONER - GENERAL PRACTICE"
```

### CONTAINS Search on One Column

```r
- dataset  Medicare Fee-For-Service Public Provider Enrollment
  column   PROVIDER_TYPE_DESC
  contains SUPPLIER

call:    /data?
          filter[example][condition][path]=PROVIDER_TYPE_DESC
         &filter[example][condition][operator]=CONTAINS
         &filter[example][condition][value]=SUPPLIER
```

### Combination Search on Two Columns

```r
- dataset  Medicare Fee-For-Service Public Provider Enrollment
  column   PROVIDER_TYPE_DESC
  contains PRACTITIONER
  column   STATE_CD
  equals   MD

call:    /data?
          filter[filter-1][condition][path]=PROVIDER_TYPE_DESC
         &filter[filter-1][condition][operator]=CONTAINS
         &filter[filter-1][condition][value]=PRACTITIONER
         &filter[filter-2][condition][path]=STATE_CD
         &filter[filter-2][condition][operator]==
         &filter[filter-2][condition][value]=MD
```

[Refer to the Drupal documentation](https://www.drupal.org/docs/core-modules-and-themes/core-modules/jsonapi-module/filtering) for more information on filtering API requests.


## Filtering and Manipulating Data

### Equals

This example is an equals filter searching the Accountable Care Organizations 2021 dataset for a single ID.

```r
https://data.cms.gov/data-api/v1/dataset/
0ece71c6-1112-47b3-8f7a-5385087e7041/data?
filter[filter-0-0][condition][path]=aco_id&
filter[filter-0-0][condition][operator]=%3D&
filter[filter-0-0][condition][value]=A4807
```

An equals filter can be simplified like this.

```r
https://data.cms.gov/data-api/v1/dataset/
0ece71c6-1112-47b3-8f7a-5385087e7041/data?
filter[aco_id]=A4807
```
### Keyword

The keyword search will look for matching words in every column. This example will check for "Alex" in the Order and Referring dataset. Notice that it finds matches on both the first and last name fields.

```r
https://data.cms.gov/data-api/v1/dataset/
c99b5865-1119-4436-bb80-c5af2773ea1f/data?
keyword=alex
```

### Multiple Conditions at Once

This search returns results from the Medicare Fee-For-Service Public Provider Enrollment dataset where the provider specialty is "PRACTITIONER - OPTOMETRY" and the location is Virginia.

```r
https://data.cms.gov/data-api/v1/dataset/
2457ea29-fc82-48b0-86ec-3b0755de7515/data?&
filter[root-group][group][conjunction]=AND&
filter[group-0][group][conjunction]=AND&
filter[group-0][group][memberOf]=root-group&
filter[filter-0-0][condition][path]=PROVIDER_TYPE_DESC&
filter[filter-0-0][condition][operator]=%3D&
filter[filter-0-0][condition][value]=PRACTITIONER%20-%20OPTOMETRY&
filter[filter-0-0][condition][memberOf]=group-0&
filter[filter-0-1][condition][path]=STATE_CD&
filter[filter-0-1][condition][operator]=%3D&
filter[filter-0-1][condition][value]=VA&
filter[filter-0-1][condition][memberOf]=group-0
```

### In

This search returns results from the Opioid Treatment Program Providers dataset where the provider is located from MD, MI, or VA with the results sorted by NPI.

```r
https://data.cms.gov/data-api/v1/dataset/
f1a8c197-b53d-4c24-9770-aea5d5a97dfb/data?
filter[condition][path]=STATE&
filter[condition][operator]=IN&
filter[condition][value][]=MI&
filter[condition][value][]=VA&
filter[condition][value][]=MD&
sort=NPI
```
