---
title: "Backend Preload"
editor_options: 
   chunk_output_type: console
---

```{r}
#| label: setup-common-01
#| include: false
source("includes/_common.R")
```

### `class_Identifier`

```{r}
#| label: class_Identifier
class_Identifier <- new_class(
  name       = "class_Identifier",
  properties = list(
    url      = new_property(
      class  = NULL | class_list,
      setter = function(self, value) {
        if (not_null(value)) {
          self@url <- url_parse(value)
          self
        }}),
    totalRows = new_property(
      class  = NULL | class_integer,
      getter = function(self) {
        if (not_null(self@url)) {
          url_build(self@url) |>
            request() |>
            req_url_path_append("stats") |>
            req_perform() |>
            resp_body_json(simplifyVector = TRUE) |>
            gelm("total_rows")
        }})
    )
)
```

### `class_Resources`

```{r}
#| label: class_Resources
class_Resources <- new_class(
  name       = "class_Resources",
  properties = list(
    url = NULL | class_character,
    files = new_property(
      class  = NULL | class_data.frame,
      getter = function(self) {
        if (not_null(self@url)) {
          qTBL(fload(self@url, query = "/data")) |>
            mtt(fileSize = prettyunits::pretty_bytes(fileSize, "nopad"))
        }})
  )
)
```

```{r}
#| label: class_API
class_API <- new_class(
  name = "class_API",
  properties = list(
    title              = class_character,
    description        = class_character,
    accrualPeriodicity = class_character,
    modified           = new_property(class_double | class_Date),
    temporal           = class_character,
    identifier         = class_Identifier,
    accessURL          = new_property(
      NULL | class_list, 
      setter = \(self, value) { 
        if (not_null(value)) { 
          self@accessURL <- request(value); 
          self 
          }
        }),
    resourcesAPI       = class_Resources,
    downloadURL        = class_character,
    describedBy        = class_character,
    landingPage        = class_character
  )
)
```


--------------------------------------------------------------------------------

## Catalog

```{r}
#| label: catalog
main <- main_data_rcpp()

main
```

### Dataset

```{r}
#| label: dataset
main[["dataset"]] |> 
  tidyr::unnest_wider(contactPoint, names_sep = "_") |>
  tidyr::unnest_wider(publisher, names_sep = "_") |> 
  collapse::frename(remove_at_symbol) |> 
  remove_all_na() |> 
  purse()
```

### Distribution

`"latest"`

```{r}
#| label: distribution_latest
main[["distribution_latest"]]
```

`"API"`

```{r}
#| label: distribution_api
main[["distribution_api"]]
```

`"text/csv"`

```{r}
#| label: distribution_csv
main[["distribution_csv"]]
```

### `S7` Sketches

#### `class_contactPoint`

```{r}
#| label: class_contactPoint
class_contactPoint <- new_class(
  name       = "class_contactPoint",
  properties = list(
    type     = new_property(class_character, 
                            default = "vcard:Contact"),
    fn       = class_character,
    hasEmail = class_character,
    hasURL   = class_character
  )
)
```

#### `class_publisher`

```{r}
#| label: class_publisher
class_publisher <- new_class(
  name       = "class_publisher",
  properties = list(
    type     = new_property(class_character, 
                            default = "org:Organization"),
    name     = new_property(class_character, 
                            default = "Centers for Medicare & Medicaid Services")
  )
)
```

#### `class_Distribution`

```{r}
#| label: class_Distribution
class_Distribution <- new_class(
  name           = "class_Distribution",
  properties     = list(
    type         = new_property(class_character, 
                                default = "dcat:Distribution"),
    format       = class_character,
    accessURL    = class_character,
    resourcesAPI = class_character,
    description  = class_character,
    title        = class_character,
    modified     = class_Date,
    temporal     = class_character,
    downloadURL  = class_character,
    mediaType    = class_character
    )
  )
```

#### `class_Dataset`

```{r}
#| label: class_Dataset
class_Dataset <- new_class(
  name = "class_Dataset",
  properties = list(
    type               = new_property(class_character, 
                                      default = "dcat:Dataset"),
    accessLevel        = new_property(class_character, 
                                      default = "public"),
    accrualPeriodicity = class_character,
    bureauCode         = new_property(class_character, 
                                      default = "009:38"),
    contactPoint       = new_property(class_contactPoint),
    describedBy        = class_character,
    dataQuality        = new_property(class_logical, 
                                      default = TRUE),
    description        = class_character,
    distribution       = class_Distribution,
    identifier         = class_character,
    keyword            = class_character,
    landingPage        = class_character,
    language           = class_character,
    license            = class_character,
    issued             = class_Date,
    modified           = class_Date,
    released           = class_Date,
    programCode        = new_property(class_character, 
                                      default = "009:000"),
    publisher          = new_property(class_publisher),
    references         = class_character,
    temporal           = class_character,
    theme              = class_character,
    title              = class_character,
    describedByType    = class_character,
    archiveExclude     = new_property(class_logical)
  ))

class_Dataset()
```

#### `class_Catalog`

```{r}
#| label: class_Catalog
class_Catalog <- new_class(
  name = "class_Catalog",
  properties = list(
    type        = new_property(class_character, 
                               default = "dcat:Catalog"),
    context     = new_property(class_character, 
                               default = "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld"),
    id          = class_character,
    conformsTo  = new_property(class_character, 
                               default = "https://project-open-data.cio.gov/v1.1/schema"),
    describedBy = new_property(class_character, 
                               default = "https://project-open-data.cio.gov/v1.1/schema/catalog.json"),
    dataset     = class_Dataset
  )
)

class_Catalog()
```

## Dataset Object

```{r}
#| label: provider_data
provider_data() |> 
  purse()
```

### National Downloadable File

```{r}
#| label: url_building
#| eval: false
httr2::url_parse("https://data.cms.gov/provider-data/api/1/datastore/query/")
    
# distro 

unclass(
  httr2::url_parse(
    "?limit=1&offset=100&count=true&results=true&schema=true&keys=true&format=json&rowIds=true"
    )
  )

ndf_identifier <- \(x) {
  kit::nswitch(x,
    "affiliations", "27ea-46a8",
    "clinicians", "mj5m-pzi6",
    default = NA_character_,
    nThread = 4L)
}

url_ndf <- httr2::url_parse(
  "https://data.cms.gov/provider-data/api/1/metastore/schemas/dataset/items/"
  )

url_tmp <- url_ndf |> 
  httr2::url_build() |> 
  httr2::request()

httr2::req_template(
  url_tmp, 
  "/{fname}?show-reference-ids=true", 
  fname = ndf_identifier("affiliations"))

url_ndf |> 
  httr2::url_build() |> 
  httr2::request() |> 
  httr2::req_url_path_append(
    ndf_identifier(fname)) |> 
  httr2::req_url_path_append("?show-reference-ids=true") |>
  httr2::req_perform() |>
  httr2::resp_body_json(check_type = FALSE, simplifyVector = TRUE)
```

```{r}
#| label: meta_ndf
meta_ndf <- \(fname) {
  
  stopifnot(curl::has_internet())
  
  x <- request(
    paste0(
      "https://data.cms.gov/",
      "provider-data/api/1/",
      "metastore/schemas/",
      "dataset/items/",
      switch(fname, 
             affiliations = "27ea-46a8", 
             clinicians   = "mj5m-pzi6", 
             stop("Invalid argument")),
    "?show-reference-ids=true")) |>
       req_perform() |>
       resp_body_json(
         check_type     = FALSE,
         simplifyVector = TRUE)
  
  distro <- gelm(gelm(x, "distribution"), "identifier")
  
  y <- request(
    paste0(
    "https://data.cms.gov/", 
    "provider-data/api/1/",
    "datastore/query/", 
    distro, 
    "?limit=1&offset=100&",
    "count=true&results=true&", 
    "schema=true&keys=true&",
    "format=json&rowIds=true")) |>
       req_perform() |>
       resp_body_json(
         check_type = FALSE,
         simplifyVector = TRUE)
  
  z <- gelm(gelm(gelm(y, "schema"), distro), "fields")
  
  list(
    title        = gelm(x, "title"),
    description  = gelm(x, "description"),
    identifier   = gelm(gelm(x, "identifier"), "identifier"),
    distribution = distro,
    issued       = gelm(x, "issued"), 
    modified     = gelm(x, "modified")[[1]], 
    released     = gelm(x, "released"),
    dimensions   = paste0(gelm(gelm(y, "count"), is.numeric), " x ", gelm(gelm(z, "record_number"), "length")), 
    fields       = names(z),
    site         = gelm(x, "landingPage"),
    csv          = gelm(gelm(gelm(x, "distribution"), "data"), "downloadURL", m = "df"),
    dictionary   = paste0("https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/physician/DOC_Data_Dictionary.pdf"))
  
}
```

### Examples

```{r}
#| label: meta_affiliations
meta_ndf("affiliations") |> purse()
```


```{r}
#| label: meta_clinicians
meta_ndf("clinicians") |> purse()
```
