---
title: "Query DSL"
editor_options: 
   chunk_output_type: console
---

```{r}
#| label: setup-common-01
#| include: false
source("includes/_common.R")

# test_url <- glue::as_glue("https://data.cms.gov/data-api/v1/dataset/d10d792e-ea6e-4145-8512-34efbc1be04b/data?size=10&offset=0&")
# 
# test_url <- test_url + greater_or_equal("overall_rating", 3)
```

## Building Queries

   1. Select Dataset/Method
   1. Build JSON Query
   1. Retrieve Number of Results
   1. Build Offset Sequence
   1. Build Request

```{.yaml}
catalog: public
  format: API
  description: latest
  title: Medicare Fee-For-Service Public Provider Enrollment
  url:
    scheme: https:
    host: data.cms.gov
    path:
      head: data-api/v1/dataset
      guid: 9887a515-7552-4693-bf58-735c77af46d7
      tail: data-viewer
      nobs: stats
    query:
      filter: 1
      path: PROVIDER_TYPE_DESC
      operator: =
      value: PRACTITIONER - GENERAL PRACTICE
```

## Operators

```{r}
#| label: allowed_operators
#| echo: false
tibble(
  ops = c("=", "<>", ">", ">=", "<", "<=", 
          "STARTS_WITH", "CONTAINS", "ENDS_WITH", 
          "IN", "NOT IN", "BETWEEN", "NOT BETWEEN", 
          "IS NULL", "IS NOT NULL"),
  impl = c("default", 
           "notequal(x)",
           "greaterthan(x)",
           "greater_or_equal(x)",
           "lessthan(x)",
           "less_or_equal(x)",
           "startswith(x)",
           "includes(x)",
           "endswith(x)",
           "in(x)",
           "notin(x)",
           "inside(x)",
           "outside(x)",
           "X",
           "X"
           )
  ) |> 
  gt() |> 
  tab_header(
    html(
      '<i>JSON<b>:</b>API</i> <span style="color:gray;"><b>Allowed Operations</b></span>'
      )
    ) |> 
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  opt_all_caps() |> 
  opt_table_lines("none") |>
  tab_options(quarto.disable_processing = TRUE, 
              column_labels.hidden = TRUE)
```

## S7

### `class_query`

```{r}
#| label: class_query
class_query <- new_class(
  "class_query",
  properties = list(
    path     = class_character,
    operator = class_character,
    value    = class_vector,
    limit    = class_numeric,
    sort     = class_character, 
    column   = class_vector,
    group    = new_property(
      class_list,
      default = list(
        conjunction = "AND",
        memberOf    = ""))
  )
)
```

### `class_args`

```{r}
#| label: class_args
null_numeric    <- new_union(NULL, class_numeric)
null_vector     <- new_union(NULL, class_vector)
null_character  <- new_union(NULL, class_character)

class_args <- new_class(
  "class_args",
  properties = list(
    id     = null_numeric,
    state  = null_character,
    name   = null_character,
    number = null_numeric
  ),
  validator = function(self) { 
    if (not_null(self@state) && 
        any(!self@state %in% state.abb)) 
      paste("`state`", self@state, "not found")
  }
)

try(class_args(
  id     = 1234567890, 
  state  = "ZZ",
  number = "300.12"))

try(class_args(
  state  = "ZZ",
  name   = "Jerry",
  number = 300.12))

class_args(state  = c("GA", "MD"))
```

## `query` Formatters

```{r}
#| label: query_test
ex <- list(
  state  = c("GA", "MD"), 
  name   = "Jerry", 
  number = 300.12)
```

### `query_comparison`

```{r}
#| label: query_comparison
query_comparison <- function(args, operator = c("=", ">", ">=", "<", "<=", "<>")) {
  
  operator <- match.arg(operator)
  args     <- args[
    cheapr::which_(
      cheapr::lengths_(
        args, 
        names = TRUE) == 1
      )]
  
  glue::glue(
  "
  filter[f{seq_along(args)}][condition][path]={names(args)}
  filter[f{seq_along(args)}][condition][operator]={operator}
  filter[f{seq_along(args)}][condition][value]={delist(args)}
  "
  )
}

query_comparison(ex)
query_comparison(ex, ">=")
```

### `query_equals_simple`

```{r}
#| label: query_equals_simple
query_equals_simple <- function(args) {
  
  args <- args[
    cheapr::which_(
      cheapr::lengths_(
        args, 
        names = TRUE) == 1
      )]
  
  glue::glue(
  "
  filter[{names(args)}]={delist(args)}
  "
  )
}

query_equals_simple(ex)
```

### `query_in_notin`

```{r}
#| label: query_in_notin
query_in_notin <- function(args, operator = c("IN", "NOT IN")) {
  
  operator <- match.arg(operator)
  args     <- args[cheapr::which_(cheapr::lengths_(args, names = TRUE) > 1)]
  
  glue::as_glue(
    c(
      glue::glue(
        "filter[f{seq_along(args)}][condition][path]={names(args)}
        filter[f{seq_along(args)}][condition][operator]={operator}"
        ), 
      glue::glue(
        "filter[f{seq_along(args)}]",
        "[condition][value]",
        "[{seq_along(delist(args))}]={delist(args)}"
        )
      )
    )
}

query_in_notin(ex)
query_in_notin(ex, "NOT IN")
```

### Finalizing `query` Components

```{r}
glue::as_glue(c(query_in_notin(ex), query_comparison(ex)))
```

### Testing in a Function

```{r}
protofunc <- function(id     = NULL, 
                      state  = NULL, 
                      name   = NULL, 
                      number = NULL) {
  arg <- class_args(
    id     = id,
    state  = state,
    name   = name,
    number = number)
  
  query_comparison(compact(props(arg)))
  
}

protofunc(state  = c("GA"), 
          name   = "Jerry", 
          number = 300.12)
```

--------------------------------------------------------------------------------

## New Function

```{r}
fields <- c(
  "year",
  "covered_recipient_npi",                                         
  "covered_recipient_type",                                        
  "covered_recipient_first_name",                                  
  "covered_recipient_last_name",                                   
  "recipient_city",                                                
  "recipient_state",                                               
  "recipient_zip_code",                                            
  "teaching_hospital_name",                                        
  "form_of_payment_or_transfer_of_value",                          
  "nature_of_payment_or_transfer_of_value",                        
  "applicable_manufacturer_or_applicable_gpo_making_payment_name",
  "applicable_manufacturer_or_applicable_gpo_making_payment_id")

process_params <- \(arg_names, field_names) {
  
  nms <- set_names(arg_names, field_names)
  
  parse_expr(
    paste0(
      "list2(", 
      glue_collapse(
        glue('{names(nms)} = {unname(nms)}'), 
        sep = ", "), ")"))
}

has_operator <- \(args) {
  map_lgl(args, function(x) inherits(x, "query_operator"))
}

name_path <- \(args) {
  map(args, \(x) x[[names(x)]][["path"]] <- names(x))
}
```


```{r}
open_pay <- function(year,
                     npi               = NULL,
                     covered_type      = NULL,
                     first             = NULL,
                     last              = NULL,
                     city              = NULL,
                     state             = NULL,
                     zip               = NULL,
                     teaching_hospital = NULL,
                     payment_form      = NULL,
                     payment_nature    = NULL,
                     payer             = NULL,
                     payer_id          = NULL) {
  
  fn_args <- process_params(fn_fmls_names(), fields) |> 
    eval_bare() |> 
    compact()
  
  # if (any(has_operator(fn_args))) fn_args[has_operator(fn_args)] <- name_path(fn_args[has_operator(fn_args)])
  
  fn_args
}
```

```{r}
open_pay(year = 2021, npi = "1043218118")
open_pay(year = 2021, payment_nature = "Royalty or License")
open_pay(year = 2021, payment_form = "Stock option")
open_pay(year = 2021, payer = "Adaptive Biotechnologies Corporation")
open_pay(year = 2021, teaching_hospital = "Nyu Langone Hospitals")
open_pay(year = 2017:2023, npi = "1043477615")
```

```{r}
starts_with <- \(x) {
  structure(
    c(path      = NA_character_,
      operator  = "STARTS_WITH",
      value     = x),
    class = "query_operator")
}

starts_with("Royalty or License")

x <- open_pay(
  year = 2021, 
  payment_nature = starts_with("Royalty or License"), 
  teaching_hospital = starts_with("NYU"))

x

names(x[has_operator(x)])

x[has_operator(x)][[1]][["path"]] <- names(x[has_operator(x)])[[1]]

x

# map(args, \(x) x[[names(x)]][["path"]] <- names(x))
# 
# x[has_operator(x)] <- providertwo:::map2(
#   x[has_operator(x)], 
#   names(x[has_operator(x)]), 
#   function(x, y) x[["path"]] <- y)
# 
# x
```


## Query Format

```{r}
url_parse(
  base_url = "https://openpaymentsdata.cms.gov/api/1/datastore/", 
  url      = "query/fdc3c773-018a-412c-8a81-d7b8a13a037b/0") |> 
  url_modify_query(
    `conditions[0][property]` = "covered_recipient_first_name",
    `conditions[0][value]`    = "PATRICK",
    `conditions[0][operator]` = "=",
    `conditions[1][property]` = "covered_recipient_last_name",
    `conditions[1][value]`    = "WARD",
    `conditions[1][operator]` = "=",
    schema                    = "false",
    keys                      = "false",
    results                   = "false",
    offset                    = 0) |>
  url_build() |> 
  request() |> 
  req_perform() |> 
  resp_body_json(simplifyVector = TRUE)
```
